import regex as re


def format_to_TeX(text: str):
    text = re.sub(r"\\\(\s+", "$", text)
    text = re.sub(r"\s+\\\)", "$", text)
    text = re.sub(r"\\\(", "$", text)
    text = re.sub(r"\\\)", "$", text)

    text = text.replace(r"\[", "$$")
    text = text.replace(r"\]", "$$")
    return text


def format_obsidian(response: list):
    for i in range(len(response)):
        append_file("out/ob.md", response[i]["problem"])


def append_file(filename: str, content: str, end="\n\n"):
    with open(filename, "a") as f:
        f.write(content + end)


if __name__ == "__main__":
    response = [
        {
            "problem": "### Problem\n\nConsider the sequence \\( \\{a_n\\} \\) given by:\n\\[\na_n = \\frac{n^2 + (-1)^n}{3n^2 + 2}.\n\\]\n\n**Part A:** Determine whether the sequence \\( \\{a_n\\} \\) is bounded. Justify your answer.\n\n**Part B:** Show that \\( \\{a_n\\} \\) is convergent, and find \\( \\lim_{n \\to \\infty} a_n \\). \n\n**Part C:** Define a function \\( f(x) = \\frac{x^2 + \\cos(x)}{3x^2 + 2} \\). Using the derivative rules (e.g., product, quotient, and chain rule), find where \\( f(x) \\) is uniformly continuous on \\((1, \\infty)\\). Hint: Consider first finding the critical points of \\( f'(x) \\) and analyzing intervals. Explore the behavior of the sequence \\( \\{a_n\\} \\) relative to uniform continuity to inform your analysis as \\( x \\to \\infty \\).",
            "solution": "### Solution\n\n**Part A:**\n\nTo determine if \\( \\{a_n\\} \\) is bounded, we observe:\n\\[\n\\left| a_n \\right| = \\left| \\frac{n^2 + (-1)^n}{3n^2 + 2} \\right| \\leq \\frac{n^2 + 1}{3n^2 + 2}.\n\\]\nFor large \\( n \\), \\( n^2 \\) dominates both the numerator and denominator, so we need to check limits:\n\\[\n\\lim_{n \\to \\infty} \\frac{n^2}{3n^2} = \\frac{1}{3}.\n\\]\n\nAdditionally, an off calculation should show\n\\[\n1 - \\epsilon \\leq \\frac{n^2 + (-1)^n}{3n^2 + 2} \\leq \\frac{1}{3} + \\epsilon,\n\\]\nwhere calculable terms inform bounding. Therefore, \\( \\{a_n\\} \\) is bounded within \\([-\\frac{1}{3}, \\frac{1}{3} + \\epsilon]\\) for small \\( \\epsilon \\).\n\n**Part B:**\n\nNotice that:\n\\[\na_n = \\frac{n^2}{3n^2} + \\frac{(-1)^n}{3n^2 + 2} \\to \\frac{1}{3},\n\\]\nas \\( n \\to \\infty \\), the influence of \\( (-1)^n \\) diminishes. To rigorously prove convergence:\n\nSince\n\\[\n\\lim_{n \\to \\infty} \\frac{(-1)^n}{3n^2 + 2} = 0 \n\\]\nby the squeeze theorem (since \\(-1/n^2 \\leq (-1)^n / (3n^2 + 2) \\leq 1/n^2\\)), we conclude:\n\\[\n\\lim_{n \\to \\infty} a_n = \\frac{1}{3}.\n\\]\nTherefore, \\( \\{a_n\\} \\) converges to \\( \\frac{1}{3} \\).\n\n**Part C:**\n\nThe derivative of \\( f(x) = \\frac{x^2 + \\cos(x)}{3x^2 + 2} \\) is:\n\\[\nf'(x) = \\frac{(2x - \\sin(x))(3x^2 + 2) - (x^2 + \\cos(x))(6x)}{(3x^2 + 2)^2}\nn= \\frac{6x^3 + 4x - 2x\\sin(x) - x^2\\cos(x) - 6x \\cos(x)}{(3x^2 + 2)^2}.\n\\]\nSolving \\( f'(x) = 0 \\), explore critical points under uniform continuity. As \\( x \\to \\infty \\), dominance by \\( 6x^3 \\) implies uniform continuity when analyzed by derivatives.\n\nEvaluate by fixing\\( C, D \\geq 0\\) where residual deritative components like \\( O(1/x^2)\\) also become negligible. \\[ f'(x) < \\epsilon, \\forall x \\in (1,\\infty)\\]\nensures the function is uniformly continuous.",
            "rubric": "### Marking Rubric\n\nPart A:\n- Correct identification and justification of the sequence \\( \\{a_n\\} \\) as bounded: 5 marks\n  - Partial credit for recognizing \\( n^2 \\) influences: 3 marks\n  - Additional attempt at the bounding technique: 2 marks\n\nPart B:\n- Correct demonstration that \\( \\{a_n\\} \\) converges: 5 marks\n  - Correct use of the limit property with \\((-1)^n\\): 3 marks\n  - Correct calculation of limit value: 2 marks\n\nPart C:\n- Derivative computation: 5 marks\n  - Special emphasis on correct application of differentiation rules\n- Critical point analysis for uniform continuity: 5 marks\n  - Bonus for exploring behavior across intervals effectively: 2 marks\n- Limits at infinity resolving continuity norm: 5 marks\n\n**Important Logic Trap:**\n- Misapplication of the Squeeze Theorem's bounds considering non-dominance (i.e., wrong acceptance of divergent terms): Deduct up to 5 marks\n- Uniform continuity errors stem from \\( f'(x)\\) handling particularly at infinities: up to 7 marks deduction.\n\nIntegrating value insights of \\( a_n \\rightarrow f(x) \\) helps escape misapplication of simple limit assumptions and deserves discretionary Officer's bonus of up to 3 marks when effectively articulated.",
        },
        {
            "problem": "Consider a sequence \\( (a_n) \\) defined recursively by \\( a_1 = \\alpha \\) (where \\( \\alpha > 0 \\)) and \\( a_{n+1} = \\frac{1}{1+a_n} \\) for \\( n \\geq 1 \\).\n\n**Part A:** Calculate \\( a_2 \\) and \\( a_3 \\) in terms of \\( \\alpha \\).\n\n**Part B:** Show that the sequence \\( (a_n) \\) is bounded and find its limit superior and limit inferior as \\( n \\to \\infty \\).\n\n**Part C:** Assume \\( f(x) = e^{-x^2} \\) and consider the sequence \\( f(a_n) \\). Using the context of uniform continuity, prove that the sequence \\( f(a_n) \\) converges to \\( f(L) \\), where \\( L \\) is the limit of the original sequence \\( (a_n) \\).\n\n**Twist:** All arguments should avoid evaluating limits directly with numerical computation. Use the properties of sequences, series, and convergence rules discussed in class.",
            "solution": "**Solution Overview:**\n\n**Part A:**\nGiven that \\( a_1 = \\alpha \\) and \\( a_{n+1} = \\frac{1}{1+a_n} \\), we find:\n- \\( a_2 = \\frac{1}{1+\\alpha} \\)\n- \\( a_3 = \\frac{1}{1+\\frac{1}{1+\\alpha}} = \\frac{1+\\alpha}{2+\\alpha} \\)\n\n**Part B:**\n- **Boundedness:** Since \\( a_{n+1} = \\frac{1}{1+a_n} \\), \\( a_n > 0 \\) implies \\( a_{n+1} < 1 \\). Hence, \\( (a_n) \\) is bounded above by 1.\n- **Limit Inferior and Limit Superior:** Since \\( a_{n+1} = \\frac{1}{1+a_n} \\), \\( a_n \\) converges if \\( a_{n+1} \\to a_n = L \\), yielding \\( L = \\frac{1}{1+L} \\). Solving \\( L^2 + L - 1 = 0 \\) gives \\( L = \\frac{-1 \\pm \\sqrt{5}}{2} \\). Only positive \\( L \\) is \\( L = \\frac{\\sqrt{5} - 1}{2} \\). Therefore, \\( \\liminf a_n = \\limsup a_n = L = \\frac{\\sqrt{5} - 1}{2} \\).\n\n**Part C:**\n- **Uniform Continuity:** The function \\( f(x) = e^{-x^2} \\) is uniformly continuous on the interval \\([0, 1]\\) as \\( f(x) \\) is a continuous function on a compact set.\n- \\( f(a_n) \\to f(L) \\): As \\( a_n \\to L = \\frac{\\sqrt{5} - 1}{2} \\), uniform continuity of \\( f(x) \\) implies \\( f(a_n) \\to f(L) = e^{-L^2} \\).\n\n**Note:** Calculators should not be used for this solution as we rely on theoretical convergence properties and algebraic manipulation.",
            "rubric": "**Marking Rubric:**\n\n**Part A:**\n- Correct expression of \\(a_2\\) in terms of \\(\\alpha\\): 2 marks\n- Correct expression of \\(a_3\\) in terms of \\(\\alpha\\): 3 marks\n- Partial marks for minor algebraic errors: 1-2 marks\n\n**Part B:**\n- Correct identification and justification of boundedness of \\((a_n)\\): 4 marks\n- Correctly solving for \\(L\\) and accurately explaining \\(\\liminf\\) and \\(\\limsup\\): 6 marks\n- Proper handling of square root in solving the quadratic equation: 2 marks\n- Deduction for incorrect limits if incorrectly argued: up to 4 marks\n\n**Part C:**\n- Correct statement of \\(f(x)\\) being uniformly continuous on [0, 1]: 3 marks\n- Detailed explanation linking sequence convergence to uniform continuity: 4 marks\n- Correct final convergence of \\((f(a_n))\\) and limiting value: 3 marks\n- Deductions for incorrect application of continuity principles: up to 2 marks\n\n**Logical Trap:**\n- Misidentification of limits as specific integers or ignoring role of recursion.\n- Over-reliance on calculator for precise values rather than algebraic manipulation.\n- Ignoring or misapplying sequence properties leading to false conclusions on limit behaviour or uniform continuity.",
        },
        {
            "problem": "**Problem Statement:**\n\nConsider the sequence \\( (a_n) \\) defined by \\( a_n = \\frac{(-1)^n n^2}{n^2 + 1} \\).\n\n---\n\n**Part A:** Show that the sequence \\((a_n)\\) is bounded.\n\n**Part B:** Prove that the sequence \\((a_n)\\) diverges. Use the definition of convergence and play against it using limit superior and limit inferior.\n\n**Part C:** Define a function \\( f(x) = \\frac{x^2}{x^2 + 1} \\) and demonstrate that \\( f(x) \\) is uniformly continuous on the set \\([0, \\infty)\\) using the concept of derivatives. Then, utilizing the result of Part B, analyze the behavior of the function \\( f(x) \\) as \\(x \\to \\infty\\) to determine the eventual behavior of the series \\( \\sum_{n=1}^{\\infty} a_n \\) by considering the convergence criteria.\n\n**Twist:** You are not allowed to directly use calculation software or standard calculators to evaluate or simplify sequences or series. Only algebraic manipulations and logical proofs with variables such as \\( n \\), \\( k \\), or \\( \\alpha \\) are allowed.",
            "solution": "**Solution:**\n\n**Part A:**\n\nTo show that the sequence \\((a_n)\\) is bounded, we need to prove \\(|a_n| \\leq 1\\) for all \\(n\\).\n\nWe have:\n\\[ a_n = \\frac{(-1)^n n^2}{n^2 + 1}. \\]\n\nTherefore, the absolute value is:\n\\[ |a_n| = \\left|\\frac{(-1)^n n^2}{n^2 + 1}\\right| = \\frac{n^2}{n^2 + 1}. \\]\n\nClearly, \\(0 \\leq \\frac{n^2}{n^2 + 1} < 1\\) since \\( n^2 < n^2 + 1\\). Therefore, \\((a_n)\\) is bounded by \\(-1\\) and \\(1\\).\n\n**Part B:**\n\nA sequence is convergent if it has a unique limit. To show \\((a_n)\\) diverges, consider the subsequences \\(a_{2n} = \\frac{(-1)^{2n} (2n)^2}{(2n)^2 + 1}\\) and \\(a_{2n+1} = \\frac{(-1)^{2n+1} (2n+1)^2}{(2n+1)^2 + 1}\\).\n\nSimplify:\n\\[ a_{2n} = \\frac{4n^2}{4n^2 + 1} \\] and \\[ a_{2n+1} = -\\frac{(2n+1)^2}{(2n+1)^2 + 1}. \\]\n\nAs \\( n \\to \\infty \\), \\( a_{2n} \\to 1 \\) and \\( a_{2n+1} \\to -1. \\) Thus, since subsequences of \\((a_n)\\) converge to different limits, \\(a_n\\) diverges.\n\n**Part C:**\n\nTo show \\( f(x) = \\frac{x^2}{x^2 + 1} \\) is uniformly continuous on \\([0, \\infty)\\), observe:\n\nDifferentiate \\( f(x) \\):\n\\[ f'(x) = \\frac{2x(x^2 + 1) - x^2 \\cdot 2x}{(x^2 + 1)^2} = \\frac{2x}{(x^2 + 1)^2}. \\]\n\nFor \\(x \\ge 0\\), \\( f'(x) \\) is continuous and bounded. Also, as \\(x \\to \\infty\\), \\( f'(x) \\to 0 \\). This confirms \\( f(x) \\) is uniformly continuous as continuous derivative decreases to zero.\n\nAs \\( x \\to \\infty, f(x) \\to 1\\). The series \\( \\sum_{n=1}^{\\infty} a_n \\) diverges by analogy with \\((a_n)\\); terms \\( a_n \\) do not shrink to zero. Hence, by the divergence test, \\(\\sum a_n\\) is divergent.",
            "rubric": "**Marking Rubric:**\n\n**Part A:**\n- Correct identification of bounds: 2 marks\n- Proper calculation using absolute value and bounding arguments: 2 marks\n- Total: 4 marks\n\n**Part B:**\n- Correct identification of subsequences \\(a_{2n}\\) and \\(a_{2n+1}\\): 1 mark\n- Proper evaluation of the limits for both subsequences: 2 marks\n- Proper conclusion about the divergence based on differing limits: 2 marks\n- Total: 5 marks\n\n**Part C:**\n- Calculating the derivative of \\(f(x)\\) accurately: 1 mark\n- Correct use of uniform continuity concept and logic: 2 marks\n- Analyzing the behavior of \\(f(x)\\) as \\(x \\to \\infty\\): 1 mark\n- Correct conclusion about the divergence of the series using convergence criteria: 3 marks\n- Total: 7 marks\n\n**Trap Alert:**\n- Students might incorrectly assume convergence based solely on some intuitions from \\((a_n)\\) boundedness without deepening into limits of subsequences.\n- Another common mistake could include misuse of continuity over an unbounded interval without derivatives support.\n- Students may forget proper divergence test justification in Part C, and it's crucial to use \\(a_n \\to 1/-1\\) implies sum divergence, not just term inequality.",
        },
    ]
    for i in range(len(response)):
        append_file("out/test.tex", format_to_TeX(response[i]["problem"]))
    import os

    # os.system("pdflatex out/test.tex")
